#!/usr/bin/env python3
"""Pack selected frames from the ansimuz zips in art-src/ into one runtime
atlas (assets/atlas_city.png) plus a generated C header of pixel rects.

All source packs are CC0 (verified in docs/ASSETS.md), so baking their frames
into a shipped atlas is licence-clean.

    python3 tools/atlaspack.py
"""

import sys
import zipfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART_SRC = ROOT / "art-src"
OUT_PNG = ROOT / "assets" / "atlas_city.png"
OUT_H = ROOT / "src" / "atlas_city.h"

# Every sprite this build needs, as (zip name, path inside zip). Order matters
# only for pack density. Frame strips list every frame explicitly rather than
# guessing a stride, since ansimuz filenames are not always zero-padded.
WARPED_CITY = "warped city files.zip"

SOURCES = {
    # -- Building facade props (windows, doors, monitors) - irregular sizes,
    # not a collision grid despite the source file's name. Kept for future
    # background dressing; ground/wall tiles stay procedural for now (see
    # game.c draw_tiles) rather than force irregular art into a tile grid.
    "tileset": (WARPED_CITY, "warped city files/Assets/ENVIRONMENT/tileset.png"),

    # -- Player, pre-built horizontal strips (71x67 per frame).
    "player_idle": (WARPED_CITY, "warped city files/Assets/SPRITESHEETS/player/idle.png"),
    "player_run":  (WARPED_CITY, "warped city files/Assets/SPRITESHEETS/player/run.png"),
    "player_jump": (WARPED_CITY, "warped city files/Assets/SPRITESHEETS/player/jump.png"),

    # -- Scrapper enemy: the drone reads as a small hostile flyer at a glance.
    "drone": (WARPED_CITY, "warped city files/Assets/SPRITESHEETS/misc/drone_preview.png"),

    # -- Parallax, back to front.
    "skyline_a": (WARPED_CITY, "warped city files/Assets/ENVIRONMENT/background/skyline-a.png"),
    "skyline_b": (WARPED_CITY, "warped city files/Assets/ENVIRONMENT/background/skyline-b.png"),
    "near_buildings": (WARPED_CITY, "warped city files/Assets/ENVIRONMENT/background/near-buildings-bg.png"),
}

PLAYER_FRAME_W = 71
PLAYER_FRAME_H = 67
DRONE_FRAME_W = 55
DRONE_FRAME_H = 52


def load(zip_name, inner_path):
    with zipfile.ZipFile(ART_SRC / zip_name) as z:
        with z.open(inner_path) as f:
            return Image.open(f).convert("RGBA").copy()


class Shelf:
    """Dumb left-to-right, wrap-at-width shelf packer. Good enough for a
    couple dozen images; a real game would reach for a proper bin packer once
    content count justifies it."""

    def __init__(self, width):
        self.width = width
        self.x = 0
        self.y = 0
        self.shelf_h = 0
        self.height = 0

    def place(self, w, h):
        if self.x + w > self.width:
            self.x = 0
            self.y += self.shelf_h
            self.shelf_h = 0
        rect = (self.x, self.y, w, h)
        self.x += w
        self.shelf_h = max(self.shelf_h, h)
        self.height = max(self.height, self.y + self.shelf_h)
        return rect


def main():
    if not ART_SRC.exists():
        print(f"error: {ART_SRC} does not exist")
        return 1

    images = {name: load(*src) for name, src in SOURCES.items()}

    shelf = Shelf(1024)
    rects = {}
    # Tallest first so the shelf packer doesn't waste rows on short strips.
    for name in sorted(images, key=lambda n: -images[n].height):
        img = images[name]
        rects[name] = shelf.place(img.width, img.height)

    atlas = Image.new("RGBA", (1024, shelf.height), (0, 0, 0, 0))
    for name, (x, y, w, h) in rects.items():
        atlas.paste(images[name], (x, y))

    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(OUT_PNG)

    aw, ah = atlas.size
    lines = [
        "/* GENERATED by tools/atlaspack.py - do not edit. */",
        "#ifndef ARC_ATLAS_CITY_H",
        "#define ARC_ATLAS_CITY_H",
        "",
        f"#define ATLAS_CITY_W {aw}",
        f"#define ATLAS_CITY_H {ah}",
        "",
        "/* x, y, w, h in atlas pixels. */",
        "typedef struct { int x, y, w, h; } arc_rect;",
        "",
    ]

    for name, (x, y, w, h) in sorted(rects.items()):
        lines.append(f"#define RECT_{name.upper()} ((arc_rect){{{x}, {y}, {w}, {h}}})")

    lines += [
        "",
        f"#define PLAYER_FRAME_W {PLAYER_FRAME_W}",
        f"#define PLAYER_FRAME_H {PLAYER_FRAME_H}",
        f"#define PLAYER_IDLE_FRAMES {images['player_idle'].width // PLAYER_FRAME_W}",
        f"#define PLAYER_RUN_FRAMES {images['player_run'].width // PLAYER_FRAME_W}",
        f"#define PLAYER_JUMP_FRAMES {images['player_jump'].width // PLAYER_FRAME_W}",
        f"#define DRONE_FRAME_W {DRONE_FRAME_W}",
        f"#define DRONE_FRAME_H {DRONE_FRAME_H}",
        f"#define DRONE_FRAMES {images['drone'].width // DRONE_FRAME_W}",
        "",
        "#endif",
    ]

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text("\n".join(lines) + "\n")

    print(f"wrote {OUT_PNG} ({aw}x{ah}) and {OUT_H}")
    for name, r in sorted(rects.items()):
        print(f"  {name:16s} {r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
