/* GENERATED by tools/atlaspack.py - do not edit. */
#ifndef ARC_ATLAS_CITY_H
#define ARC_ATLAS_CITY_H

#define ATLAS_CITY_W 1024
#define ATLAS_CITY_H 584

/* x, y, w, h in atlas pixels. */
typedef struct { int x, y, w, h; } arc_rect;

#define RECT_DRONE ((arc_rect){0, 532, 220, 52})
#define RECT_NEAR_BUILDINGS ((arc_rect){0, 256, 493, 209})
#define RECT_PLAYER_IDLE ((arc_rect){493, 256, 284, 67})
#define RECT_PLAYER_JUMP ((arc_rect){568, 465, 355, 67})
#define RECT_PLAYER_RUN ((arc_rect){0, 465, 568, 67})
#define RECT_SKYLINE_A ((arc_rect){384, 0, 128, 240})
#define RECT_SKYLINE_B ((arc_rect){512, 0, 128, 240})
#define RECT_TILE_BAND ((arc_rect){236, 532, 16, 16})
#define RECT_TILE_FILL ((arc_rect){252, 532, 16, 16})
#define RECT_TILE_TOP ((arc_rect){220, 532, 16, 16})
#define RECT_TILESET ((arc_rect){0, 0, 384, 256})

#define PLAYER_FRAME_W 71
#define PLAYER_FRAME_H 67
#define PLAYER_IDLE_FRAMES 4
#define PLAYER_RUN_FRAMES 8
#define PLAYER_JUMP_FRAMES 5
#define DRONE_FRAME_W 55
#define DRONE_FRAME_H 52
#define DRONE_FRAMES 4

#endif
